version: "3.7"
services:
  apim-connector:
    container_name: openshift-example-apim-connector
    image: "solaceiotteam/apim-connector-server:0.3.0"
    # image: "solaceiotteam/apim-connector-server:latest"
    ports:
      - 9098:3000
    volumes:
      - ./docker-volumes/apim-connector:/data
    restart: unless-stopped
    environment:
      # DB-URL="mongodb://{admin-user}:{admin-password}@localhost:{external-port}/{db-name}?retryWrites=true"
      # host.docker.internal for MAC
      - DB_URL=mongodb://admin:${MONGODB_ADMIN_PASSWORD}@host.docker.internal:${MONGODB_EXTERNAL_PORT}/admin?retryWrites=true&w=majority
      # - DB_URL=mongodb://admin:${MONGODB_ADMIN_PASSWORD}@localhost:${MONGODB_EXTERNAL_PORT}/admin?retryWrites=true&w=majority
      - LOG_LEVEL=trace
      - APP_ID="openshift-connector"
      - FILE_USER_REGISTRY=/data/organization_users.json
      - PLATFORM_PORT=3000
      - AUTH_EXTRACTION_USER_PRINCIPAL="$$.preferred_username"
      - AUTH_EXTRACTION_ORGS="$$.organization"
      - AUTH_EXTRACTION_ROLES="$$.groups"
      - AUTH_VERIFICATION_KEY=/data/dummy.pem
      - AUTH_VERIFICATION_ISSUER="https://dev-1.okta.com/oauth2/default"
      - AUTH_VERIFICATION_AUD="0oancf26sFegoXz8l5d6"
      - AUTH_DISCOVERY_OIDC_URL=https://dev-1.okta.com/x/oauth2/default/.well-known/openid-configuration
