- name: generate INVENTORY.MD
  hosts: 127.0.0.1
  connection: local

  tasks:
    - include_vars: "{{ lookup('env','SOLINVENTORY_CONFIG') or '../vars' }}/{{ item }}"
      loop:
        - ansible_vars.yml

    - include_vars: "{{sensitive_ansible_vars_file}}"


    - debug: msg="Play ok"