# Registers IP withcloud.mongodb
- name: Remove IP with cloud.mongodb
  hosts: 127.0.0.1

  tasks:
    - include_vars: "{{ lookup('env','SOLINVENTORY_CONFIG') or '../vars' }}/ansible_vars.yml"
    - include_vars: "{{sensitive_ansible_vars_file}}"
    - include_vars: "{{generated_infrastructure_vars_file}}"

    - name: Remove IP with cloud.mongdo
      uri:
        url: "{{ mongodb_cloud_api_url }}/{{ platform_api_host_ip }}"
        method: DELETE
        body_format: json
        user: "{{mongodb_cloud_api_user}}"
        password: "{{mongodb_cloud_api_password}}"
        status_code: 204