
# ##################################################################################################################################
# mapping of use case boostrap env to system env
# APIM SYSTEM SPECIFIC ENVIRONMENT
export APIM_SYSTEM_PROJECT_NAME="apim-reference"
export APIM_SYSTEM_CONNECTOR_SERVER_DATA_VOLUME_MOUNT=$APIM_BOOTSTRAP_CONNECTOR_SERVER_DATA_VOLUME_MOUNT
export APIM_SYSTEM_CONNECTOR_SERVER_FILE_USER_REGISTRY=$APIM_BOOTSTRAP_CONNECTOR_SERVER_FILE_USER_REGISTRY
export APIM_SYSTEM_CONNECTOR_SERVER_PORT=$APIM_BOOTSTRAP_CONNECTOR_SERVER_PORT
export APIM_SYSTEM_CONNECTOR_SERVER_DOCKER_IMAGE=$APIM_BOOTSTRAP_CONNECTOR_SERVER_DOCKER_IMAGE
export APIM_SYSTEM_CONNECTOR_EVENT_PORTAL_APIS_PROXY_MODE=$APIM_BOOTSTRAP_CONNECTOR_EVENT_PORTAL_APIS_PROXY_MODE
# JWT token validation properties
export APIM_SYSTEM_CONNECTOR_SERVER_AUTH_EXTRACTION_USER_PRINCIPAL=$.upn
export APIM_SYSTEM_CONNECTOR_SERVER_AUTH_EXTRACTION_ORGS=$.groups
export APIM_SYSTEM_CONNECTOR_SERVER_AUTH_EXTRACTION_ROLES=$.resource_access['platform-api-server'].roles
export APIM_SYSTEM_CONNECTOR_SERVER_AUTH_VERIFICATION_KEY="jwt_dummy.pem"
export APIM_SYSTEM_CONNECTOR_SERVER_AUTH_VERIFICATION_ISSUER=http://localhost:8180/auth/realms/default
export APIM_SYSTEM_CONNECTOR_SERVER_AUTH_VERIFICATION_AUD=platform-api-server
export APIM_SYSTEM_CONNECTOR_SERVER_AUTH_DISCOVERY_OIDC_URL=http://localhost:8180/auth/realms/default/.well-known/openid-configuration
# demo portal
export APIM_SYSTEM_DEMO_PORTAL_SERVER_PORT=$APIM_BOOTSTRAP_DEMO_PORTAL_SERVER_PORT
export APIM_SYSTEM_DEMO_PORTAL_SERVER_DOCKER_IMAGE=$APIM_BOOTSTRAP_DEMO_PORTAL_SERVER_DOCKER_IMAGE
export APIM_SYSTEM_DEMO_PORTAL_ORG_API_USER=$APIM_BOOTSTRAP_DEMO_PORTAL_USER
export APIM_SYSTEM_DEMO_PORTAL_ORG_API_USER_PWD=$APIM_BOOTSTRAP_DEMO_PORTAL_USER_PWD
export APIM_SYSTEM_DEMO_PORTAL_ADMIN_USER=$APIM_BOOTSTRAP_ADMIN_USER
export APIM_SYSTEM_DEMO_PORTAL_ADMIN_USER_PWD=$APIM_BOOTSTRAP_ADMIN_USER_PWD

# DEACTIVATE ENVIRONMENT
deactivate-apim-env () {
    x=$(env | grep APIM | egrep -o '^[^=]+')
    unset $x
    env | grep APIM
    unset -f deactivate-apim-env
}
