# Stops docker containers 
# Unmounts EBS filesystem to be able to destroy infrastructure via Terraform
- name: Preparing to destroy infrastructure
  hosts: docker_hosts


  tasks:
    - name: stop platform-api services 
      docker_compose:
        project_src: /opt/platform-api/docker
        state: absent
      become: yes
      ignore_errors: yes

- name: Preparing to destroy infrastructure
  hosts: mount_ebs

  tasks:
    - name: Unmount filesystem
      mount:
        path: /data
        src: /dev/xvdh
        fstype: ext4
        state: unmounted
      become: yes
      ignore_errors: yes




