
# Usage:
# cp template.source.env.sh source.env.sh
# vi source.env.sh
# <enter values>
# source source.env.sh

scriptDir=$(pwd)
# USE CASE SPECIFIC BOOTSTRAP ENVIRONMENT
export APIM_BOOTSTRAP_USE_CASE_NAME="uc-elevator-co"
export APIM_BOOTSTRAP_DEMO_PORTAL_SERVER_PORT=9091
export APIM_BOOTSTRAP_CONNECTOR_SERVER_PROTOCOL="http"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_PORT=9090
export APIM_BOOTSTRAP_CONNECTOR_SERVER_HOST="localhost"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_ORG_NAME="elevator-co"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_ORG_API_USER="elevator_co_admin"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_ORG_API_USER_PWD="elevator_co_admin_123!"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_ADMIN_USER="{admin-user}"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_ADMIN_USER_PWD="{admin-user-secret}"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_SOLACE_CLOUD_API_URL="https://api.solace.cloud/api/v0"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_SOLACE_CLOUD_TOKEN="{solace-cloud-token}"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_SOLACE_EVENT_PORTAL_API_URL="https://api.solace.cloud/api/v0"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_SOLACE_EVENT_PORTAL_TOKEN="{solace-event-portal-token}"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_SOLACE_CLOUD_DEV_GW_SERVICE_ID="{solace-cloud-dev-gateway-service-id}"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_SOLACE_CLOUD_PROD_GW_SERVICE_ID="{solace-cloud-prod-gateway-service-id}"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_DATA_VOLUME_MOUNT="$scriptDir/apim-connector-data"
export APIM_BOOTSTRAP_CONNECTOR_SERVER_FILE_USER_REGISTRY="organization_users.json"
env | grep APIM_BOOTSTRAP

# APIM SYSTEM SPECIFIC ENVIRONMENT
export APIM_SYSTEM_PROJECT_NAME=$APIM_BOOTSTRAP_USE_CASE_NAME
export APIM_SYSTEM_CONNECTOR_SERVER_DATA_VOLUME_MOUNT=$APIM_BOOTSTRAP_CONNECTOR_SERVER_DATA_VOLUME_MOUNT
export APIM_SYSTEM_CONNECTOR_SERVER_FILE_USER_REGISTRY=$APIM_BOOTSTRAP_CONNECTOR_SERVER_FILE_USER_REGISTRY
export APIM_SYSTEM_CONNECTOR_SERVER_ORG_API_USER=$APIM_BOOTSTRAP_CONNECTOR_SERVER_ORG_API_USER
export APIM_SYSTEM_CONNECTOR_SERVER_ORG_API_USER_PWD=$APIM_BOOTSTRAP_CONNECTOR_SERVER_ORG_API_USER_PWD
export APIM_SYSTEM_CONNECTOR_SERVER_ADMIN_USER=$APIM_BOOTSTRAP_CONNECTOR_SERVER_ADMIN_USER
export APIM_SYSTEM_CONNECTOR_SERVER_ADMIN_USER_PWD=$APIM_BOOTSTRAP_CONNECTOR_SERVER_ADMIN_USER_PWD
export APIM_SYSTEM_CONNECTOR_SERVER_PORT=$APIM_BOOTSTRAP_CONNECTOR_SERVER_PORT
export APIM_SYSTEM_DEMO_PORTAL_SERVER_PORT=$APIM_BOOTSTRAP_DEMO_PORTAL_SERVER_PORT

# DEACTIVATE ENVIRONMENT
apim-env-bootstrap-deactivate () {
    x=$(env | grep APIM_BOOTSTRAP | egrep -o '^[^=]+')
    unset $x
    env | grep APIM_BOOTSTRAP
    x=$(env | grep APIM_SYSTEM | egrep -o '^[^=]+')
    unset $x
    env | grep APIM_SYSTEM
    unset -f apim-bootstrap-deactivate
}
